CREATE TABLE DESENVOLVEDORES (
ID INT NOT NULL AUTO_INCREMENT,
NOME_COMPLETO VARCHAR(40) NOT NULL,
CPF   CHAR(11) NOT NULL,
DATA_NASCTO DATE,
GENERO  ENUM('MASCULINO','FEMININO','N.A'),
ESTADO_CIVIL ENUM('CASADO', 'SOLTEIRO', 'DIVORCIADO', 'AMASIADO'),
NRO_FILHOS INT,
NACIONALIDADE VARCHAR (30),
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT PK_DESENVOLVEDORS PRIMARY KEY (ID)
);
CREATE TABLE HABILIDADES (
ID INT NOT NULL AUTO_INCREMENT,
ID_DEV INT NOT NULL,
TITULO VARCHAR(30) NOT NULL,
DESCRICAO VARCHAR(200),
TEMPO_EXPERIENCIA INT NOT NULL,
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT PK_HABILIDADES PRIMARY KEY (ID),
CONSTRAINT FK_HABILIDADES_DESENVOLVEDORES FOREIGN KEY (ID_DEV) REFERENCES DESENVOLVEDORES (ID));
CREATE TABLE EMPRESAS (
ID INT NOT NULL AUTO_INCREMENT,
NOME_EMP  VARCHAR(40) NOT NULL,
SEDE VARCHAR(50),
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT PK_EMPRESAS PRIMARY KEY (ID));

CREATE TABLE ENDERECOS (
ID INT NOT NULL AUTO_INCREMENT,
ID_ENDERECO INT NOT NULL,
LOGRADOURO VARCHAR(45),
ESTADO     VARCHAR(15),
CIDADE     VARCHAR(30),
CEP        VARCHAR(10),
CIDADE_NASCIMENTO VARCHAR(35),
ESTADO_NASCIMENTO VARCHAR(15),
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT PK_ENDERECOS PRIMARY KEY (ID),
CONSTRAINT FK_ENDERECOS_EMPRESAS FOREIGN KEY (ID_ENDERECO) REFERENCES EMPRESAS (ID) ON UPDATE CASCADE,
CONSTRAINT FK_ENDERECOS_DESENVOLVEDORES FOREIGN KEY (ID_ENDERECO) REFERENCES DESENVOLVEDORES (ID) ON UPDATE CASCADE
);
CREATE TABLE CONTAS(
ID INT NOT NULL AUTO_INCREMENT,
ID_ACC INT NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
PASSWRD  VARCHAR(128),
ACC_STATUS ENUM('DESATIVADA', 'ATIVA', 'BLOQUEADA', 'INATIVA'),
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT PK_CONTAS PRIMARY KEY (ID),
CONSTRAINT FK_CONTAS_EMPRESAS FOREIGN KEY (ID_ACC) REFERENCES EMPRESAS(ID) ON UPDATE CASCADE,
CONSTRAINT FK_CONTAS_DESENVOLVEDORES FOREIGN KEY (ID_ACC) REFERENCES DESENVOLVEDORES(ID) ON UPDATE CASCADE
);
CREATE TABLE RECUPERAR_CONTAS (
ID INT NOT NULL AUTO_INCREMENT,
CODIGO INT NOT NULL,
ID_ACC INT NOT NULL,
STATUS_RECUPERACAO ENUM('RECUPERADO', 'EXPIRADO', 'REJEITADO'),
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT PK_RECUPERAR_CONTAS PRIMARY KEY (ID),
CONSTRAINT FK_RECUPERAR_CONTAS_CONTAS FOREIGN KEY (ID_ACC) REFERENCES CONTAS (ID) ON UPDATE CASCADE
);
CREATE TABLE VAGAS(
ID INT NOT NULL AUTO_INCREMENT,
ID_EMPRESA INT NOT NULL,
TITULO  VARCHAR(40),
DESCRICAO  VARCHAR(600),
MEDIA_LINK VARCHAR(300),
MIN_SALARIO  DECIMAL(10,4),
MAX_SALARIO DECIMAL(10,4),
DATA_INICIO   DATE,
DATA_FIM      DATE,
STATUS_VAGA  ENUM('CANCELADA', 'PRORROGADA', 'ATIVA', 'FINALIZADA'),
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT PK_VAGAS PRIMARY KEY (ID),
CONSTRAINT FK_VAGAS_EMPRESAS FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS (ID) ON UPDATE CASCADE
);

CREATE TABLE CANDIDATURAS (
ID INT NOT NULL AUTO_INCREMENT,
ID_VAGA INT NOT NULL,
ID_DESENVOLVEDOR INT NOT NULL,
DATA_CANDIDATURA DATETIME,
STATUS_CANDIDATURA ENUM('CANCELADA','ATIVA', 'DESATIVADA', 'FINALIZADA'),
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT PK_CANDIDATURAS PRIMARY KEY (ID),
CONSTRAINT FK_CANDIDATURAS_DESENVOLVEDORES FOREIGN KEY (ID_DESENVOLVEDOR) REFERENCES DESENVOLVEDORES(ID) ON UPDATE CASCADE,
CONSTRAINT FK_CANDIDATURAS_VAGAS FOREIGN KEY (ID_VAGA) REFERENCES VAGAS(ID) ON UPDATE CASCADE);

CREATE TABLE CONTATO_CANDIDATURAS (
ID INT NOT NULL AUTO_INCREMENT,
ID_CANDIDATURA INT NOT NULL,
ID_EMPRESA INT NOT NULL,
ID_DESENVOLVEDOR INT NOT NULL,
TITULO_MENSAGEM VARCHAR(50),
MENSAGEM VARCHAR(600),
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT PK_CONTATO_CANDIDATURAS PRIMARY KEY (ID),
CONSTRAINT FK_CONTATO_CANDIDATURAS_EMPRESAS FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID) ON UPDATE CASCADE,
CONSTRAINT FK_CONTATO_CANDIDATURAS_DESENVOLVEDOR FOREIGN KEY (ID_DESENVOLVEDOR) REFERENCES DESENVOLVEDORES (ID) ON UPDATE CASCADE,
CONSTRAINT FK_CONTATO_CANDIDATURAS_CANDIDATURAS FOREIGN KEY (ID_CANDIDATURA) REFERENCES CANDIDATURAS (ID) ON UPDATE CASCADE );
